backend:
  name: github
  repo: YOUR_GITHUB_USERNAME/YOUR_REPOSITORY_NAME # e.g. sahil/miracle-kids
  branch: main
  auth_type: pkce

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "notices"
    label: "Notices"
    files:
      - file: "data/notices.json"
        label: "Notice List"
        name: "notices_list"
        fields:
          - label: "Notices"
            name: "items"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Details", name: "detail", widget: "text" }
              
